name: validate-bicep

on:
  workflow_call:
    inputs:
      AZURE_ACCESSTOKEN:
        required: true
        description: AZURE_SECRETS
        type: string
      RESOURCEGROUP_NAME:
        required: true
        description: Resource group name
        type: string
      SUBSCRIPTION_ID:
        required: true
        description: Subscription ID
        type: string
      TEMPLATE_NAME:
        required: true
        description: Template filename
        type: string
      ENVIRONMENT:
        required: true
        description: Name of folder where parameters reside
        type: string

jobs:
  deploy-bicep:
    name: Deploy bicep template
    runs-on: ubuntu-latest
    steps:
      # Log into Azure with SPN
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: 'TEMPLATE_NAME'

      # Deploy Code
      - name: deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ inputs.SUBSCRIPTION_ID }}
          resourceGroupName: ${{ inputs.RESOURCEGROUP_NAME }}
          template: bicep/${{ inputs.TEMPLATE_NAME }}.bicep
          parameters: bicep/parameters/${{ inputs.ENVIRONMENT }}/${{ inputs.TEMPLATE_NAME }}.parameters.json
          failOnStdErr: false
          additionalArguments: --what-if